### ISSUE TITLE
导航栏隐藏效果

### ISSUE THREAD

**Issue by Kevinlwg** [imwangxuesen/JsenProjectEncapsulation#4]
大神你好，请问在导航栏下面加一个segment呢，隐藏导航栏之后segment占据导航栏的位置，这种效果如何实现呢？望大神最好是能写个demo，十分感谢！

**Comment by imwangxuesen** [comment]
@Kevinlwg 我没有太明白你的“隐藏导航栏”这个动作的含义，一开始segment不再页面上显示吗？是segment一直被导航栏覆盖吗？然后导航栏透明度如果变为0，就可以看到segment那种？如果是，最简单的思路就是将view的frame从屏幕的左上角开始布局，然后在一开始加载视图就加入segment，操作导航栏的位置，自然就可以个看到segment

**Comment by Kevinlwg** [comment]
不是。你看一下最新版淘宝的“微淘”页面，上滑隐藏导航栏的过程。导航栏可以有任意高度的中间状态。
