### ISSUE TITLE
不是。你看一下最新版淘宝的“微淘”页面，上滑隐藏导航栏的过程。

### ISSUE THREAD

**Issue by Kevinlwg** [imwangxuesen/JsenProjectEncapsulation#5]
不是。你看一下最新版淘宝的“微淘”页面，上滑隐藏导航栏的过程。

**Comment by imwangxuesen** [comment]
首先你看懂，至少会用我写的那个导航栏上滑隐藏的功能，让后同理在滚动视图上加一个视图，让他根据你的偏移量移动，超出一定范围不移动，里边的图片消失和文字变化也是根据偏移量改变的，并且你仔细看就发现这个view 的大小始终没有变化，改变的是里边文字和图片的大小，不知道说这样你能否明白

**Comment by Kevinlwg** [comment]
嗯，谢谢你！

**Comment by Kevinlwg** [comment]
大神，有几个问题想向你请教一下，看了你的demo，我实现的时候，NavigationBar隐藏的效果是直接显示和隐藏。没有达到你的“设置”导航栏能隐藏任意高度的效果。能留一个联系方式吗？或者你加我QQ：474725133也行。谢谢

**Comment by imwangxuesen** [comment]
你看怎么去移动和隐藏导航栏，让后根据你自己需求在特定的点去做特定的动作，你把你要做的效果细分成多个关键点，让后一个阶段一个阶段的去分析实现，这样应该会比你直接全部想要简单很多，不要被我的思路禁锢住，也不要指望有人可以帮你，大家都是来交流思想，不是代码。加油

**Comment by Kevinlwg** [comment]
嗯，谢谢指点。

**Comment by imwangxuesen** [comment]
@Kevinlwg 客气了，加油
